### PR TITLE
Improvements on the UI side

### PR DESCRIPTION
**Pull request by Vazquinhos**
The UI layout is improved. ( see preview.png ) 
Data context also is used for getting the file selected

### CODE REVIEW

**Comment by Aionmagan** [comment]
> The UI layout is improved. ( see preview.png ) Data context also is used for getting the file selected

hey sorry i didn't see this commit, i'm not actively using Github, but i also think this tool is no longer in need 
or useful due to how much you can now do from with in the switch 

if you still want me to merge i'll check everything out in detail and merge (only if there is an executable ready since i do not have my window enviroment set up since 2019)

**Comment by Vazquinhos** [comment]
Hey, I was using it as I am an oled school guy xD

**Review by Aionmagan — COMMENTED** [review]
a lot of changes, too much to check, if it breaks i'll revert it back to the old one

**Comment by Aionmagan** [comment]
> Hey, I was using it as I am an oled school guy xD 

if possible send a compiled .exe, as i don't have windows accesseble to me right now

**Pull request merged**
